Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.15.20.61"

  config.vm.synced_folder ".", "/home/vagrant/share"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "deep_master"
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      vb.customize ["modifyvm", :id, "--pae", "on"]
      vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end
