Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.15.20.65"

  config.vm.synced_folder ".", "/home/vagrant/share"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "deep_slave"
      vb.memory = "2048"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      vb.customize ["modifyvm", :id, "--pae", "on"]
      vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
  end
  
end
