Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"

  config.vm.network "private_network", ip: "10.15.20.55"
#  config.vm.network "forwarded_port", host: 8080, guest: 8080

  config.vm.synced_folder "../../", "/home/vagrant/work"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "nodeWorkstation"
      vb.memory = "1024"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "25"]
      vb.customize ["modifyvm", :id, "--pae", "on"]
      vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end
