# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "aws_shell"
  config.vm.synced_folder ".", "/home/vagrant/share", disabled: true

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAJUF6RZ2U2BNQIZYA"
    aws.secret_access_key = "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"
    aws.region = "us-west-2"
    aws.keypair_name = "DeepMarkit_Private"

    aws.ami = "ami-63ac5803"

    aws.instance_type = "t2.medium"
    aws.associate_public_ip = "false"
    aws.ssh_host_attribute = ":private_ip_address"
    aws.security_groups = "sg-03331066"
    aws.subnet_id = "subnet-d89d10bd"
    
    aws.tags = {
      'Name' => '_PRIVATE: Deploy Agent'
    }
    
    aws.block_device_mapping = [
      { 
        'DeviceName' => '/dev/sda1', 
        'Ebs.VolumeSize' => 50 
      }
    ]

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "C:\\Users\\nolan\\.ssh\\DeepMarkit_Private.pem"

    config.vm.provision :shell, path: "bootstrap.sh"
    
  end
end